export const CREATE_FEEDBACK= "CREATE_FEEDBACK";
export const RETRIEVE_FEEDBACKS = "RETRIEVE_FEEDBACKS";
export const UPDATE_FEEDBACK = "UPDATE_FEEDBACK";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
export const DELETE_ALL_FEEDBACKS = "DELETE_ALL_FEEDBACKS";
